const ACTION_TYPES = Object.freeze({
  ADD_HACKER_APPLICATION: 'ADD_HACKER_APPLICATION',
  CHANGE_HACKER_APPLICATION_PAGE: 'CHANGE_HACKER_APPLICATION_PAGE',
  CHANGE_HACKER_APPLICATION_LAST_VALID_INDEX: 'CHANGE_HACKER_APPLICATION_LAST_VALID_INDEX',
  CANCEL_HACKER_APPLICATION: 'CANCEL_HACKER_APPLICATION',
  RESET_HACKER_UI: 'RESET_HACKER_UI',
  ADD_VOLUNTEER_APPLICATION: 'ADD_VOLUNTEER_APPLICATION',
  CHANGE_VOLUNTEER_APPLICATION_PAGE: 'CHANGE_VOLUNTEER_APPLICATION_PAGE',
  CHANGE_VOLUNTEER_APPLICATION_LAST_VALID_INDEX: 'CHANGE_VOLUNTEER_APPLICATION_LAST_VALID_INDEX',
  CANCEL_VOLUNTEER_APPLICATION: 'CANCEL_VOLUNTEER_APPLICATION',
  RESET_VOLUNTEER_UI: 'RESET_VOLUNTEER_UI',
});

export default ACTION_TYPES;
