const ACTION_TYPES = Object.freeze({
  ADD_HACKER_APPLICATION: 'ADD_HACKER_APPLICATION',
  CHANGE_HACKER_APPLICATION_PAGE: 'CHANGE_HACKER_APPLICATION_PAGE',
  CHANGE_HACKER_APPLICATION_LAST_VALID_INDEX: 'CHANGE_HACKER_APPLICATION_LAST_VALID_INDEX',
  CANCEL_HACKER_APPLICATION: 'CANCEL_HACKER_APPLICATION',
});

export default ACTION_TYPES;
