export const schools = [
  'British Columbia Institute of Technology',
  'Capilano University',
  'Carleton University',
  'Columbia College',
  'Concordia University',
  'Douglas College',
  'Eastern Washington University',
  'Emily Carr University of Art and Design',
  'Kwantlen Polytechnic University',
  'Langara College',
  'McGill University',
  'McMaster University',
  'Polytechnique Montréal',
  "Queen's University",
  'Quest University Canada',
  'Ryerson University',
  'Simon Fraser University',
  'Thompson Rivers University',
  'Trinity Western University',
  'University of Alberta',
  'University of British Columbia (Okanagan)',
  'University of British Columbia (Vancouver)',
  'University of Calgary',
  'University of Lethbridge',
  'University of Northern British Columbia',
  'University of Ottawa',
  'University of the Fraser Valley',
  'University of Toronto',
  'University of Victoria',
  'University of Washington',
  'University of Waterloo',
  'Vancouver Community College',
  'Vancouver Island University',
  'Washingston State University',
  'Western University',
  'Wilfrid Laurier University',
];
