export const majors = [
  'Accounting',
  'Archaeology',
  'Anthropology',
  'Art',
  'Astronomy',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Biophysics',
  'Biotechnology',
  'Business Administration',
  'Chemical and Biological Engineering',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Cognitive Systems (Arts)',
  'Cognitive Systems (Science)',
  'Combined Major in Business and Computer Science',
  'Combined Major in Mathematics and Computer Science',
  'Combined Major in Mathematics and Statistics',
  'Combined Major in Physics and Computer Science',
  'Commerce',
  'Computer Engineering',
  'Computer Science (Arts)',
  'Computer Science (Science)',
  'Creative Writing',
  'Earth and Ocean Sciences',
  'Economics',
  'Electrical Engineering',
  'Engineering Physics',
  'English',
  'Entrepreneurship',
  'Finance',
  'Fine Arts',
  'Food & Nutritional Sciences',
  'Forestry',
  'Geography',
  'Geology',
  'History',
  'Integrated Sciences',
  'International Relations',
  'Kinesiology',
  'Law',
  'Marketing',
  'Mathematical Sciences',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Microbiology',
  'Microbiology and Immunology',
  'Music',
  'Pharmaceutical Science',
  'Pharmacology',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Sociology',
  'Statistics',
  'Undeclared/Undecided',
  'Visual Arts',
];
