export const majors = [
  'Accounting',
  'Accounting Co-op',
  'Accounting Sub-Specialization',
  'Adult Education',
  'Adult Learning & Global Change',
  'Adult Learning and Education',
  'Advanced Materials Manufact',
  'African Studies',
  'Agricultural Economics',
  'Agroecology',
  'Anatomy & Cell Biology',
  'Ancient Culture,Religion & Ethn',
  'Animal Science',
  'Animal Studies',
  'Anthropological Archaeology',
  'Anthropology',
  'Applied Animal Biology',
  'Applied Music Technology',
  'Applied Plant & Soil Sciences',
  'Appraisal',
  'Arc & Hist Greece, Rome & NearEast',
  'Art',
  'Art Education',
  'Art History & Visual Culture',
  'Arts',
  'Asian Area Studies',
  'Asian Cdn & Asian Migration St',
  'Asian Language & Culture',
  'Asian Studies',
  'Astronomy',
  'Atmospheric Science',
  'Audiology & Speech Sciences',
  'Biochemistry',
  'Biochemistry & Forensic Sci',
  'Biochemistry & Molecular Biol',
  'Bioinformatics',
  'Biological Science',
  'Biology',
  'Biomedical Engineering',
  'Biophysics',
  'Bio-Resource Engineering',
  'Biotechnology',
  'Bisc Fren Immersion 12mo',
  'Botany',
  'Business Administration',
  'Business Education',
  'Business Innovation',
  'Business Intell Syst SubSpec',
  'Business Technology Mgmt',
  'Canadian Studies',
  'Career Education  - Chef Spec',
  'Career Prep - Chef Instructors',
  'Cell & Developmental',
  'Cell, Anatomical & Physiol Sci',
  'Cell Biol and Genetics',
  'Chem Fren Immersion 12mo',
  'Chemical & Biol Engineering',
  'Chemical Biology',
  'Chemical Eng-Chem Honours',
  'Chemical Engineering',
  'Chemistry',
  "Children's Literature",
  'Chinese',
  'Civil Engineering',
  'Classic & Near East Archaeology',
  'Classics',
  'Class, N. Eastern & Relg. Studies',
  'Clean Energy Engineering',
  'Climatology',
  'Cognitive Systems (Arts)',
  'Cognitive Systems (Science)',
  'Commerce',
  'Community & Regional Planning',
  'Composition',
  'Comprehensive',
  'Computer Engineering',
  'Computer Science (Arts)',
  'Computer Science (Science)',
  'Computing Studies Education',
  'Conducting',
  'Consulting & Strategic Mgmt',
  'Co-operative Education',
  'Counselling Psychology',
  'Craniofacial Science',
  'Creative Writing',
  'Creative Writing/Theatre',
  'Critical Curatorial Studies',
  'Critical Studies in Sexuality',
  'Cross-Faculty Inquiry in Educ',
  'Curriculum & Leadership',
  'Curriculum Studies',
  'Dependable Software Systems',
  'Development',
  'Dietetics',
  'Direct Entry',
  'Early Childhood Education',
  'Early Years Education',
  'Earth & Space Science',
  'Earth and Ocean Sciences',
  'Earth Sciences',
  'Economics',
  'Economics & Political Science',
  'Economics & Statistics',
  'Economics and Mathematics',
  'Economics and Philosophy',
  'Education',
  'Educational Admin & Leadership',
  'Educational Studies',
  'Education of Young Children',
  'Educ Curric & Instruct Studies',
  'Educ. Leadership & Policy',
  'Electrical & Computer Eng',
  'Electrical Eng',
  'Electro-Mechanical Design Eng',
  'Engineering Physics',
  'English',
  'English As Additional Lang',
  'English Language Learners Ed',
  'Entrepreneurship',
  'Entrepreneurship & Intl. Bus',
  'Entrepreneurship Commerce',
  'Entrepreneurship SubSpec',
  'Environmental Engineering',
  'Environmental Sciences',
  'Environment and Society',
  'Essc Fren Immersion 12mo',
  'Ethnomusicology',
  'European Studies',
  'Experimental Medicine',
  'Expressive Arts in Education',
  'Family cons serv clothing/text',
  'Family Cons Serv/Food & Nutri',
  'Family Life Education',
  'Family Studies',
  'Film Production',
  'Film Production/Creative Writ',
  'Film Studies',
  'Finance',
  'Finance & Internat. Business',
  'Financial Accounting',
  'Fine Arts',
  'First Nations & Endangered Lang',
  'First Nations & Indigenous Stud',
  'First Nations Languages & Ling',
  'First Nations Studies',
  'Fisheries Oceanography',
  'Food & Nutr Sciences',
  'Food And Resource Economics',
  'Food and the Environment',
  'Food Market Analysis',
  'Food, Nutrition & Health',
  'Food Science',
  'Forest Operations',
  'Forest Resources Management',
  'Forestry',
  'Forest Sciences',
  'Foundations',
  'French',
  'French Education 12 Month',
  'Fren Immersion Educ',
  'Gender Race Sexuality Social Just',
  'General Biology',
  'General Business Mgmt',
  'General Studies',
  'General Studies Elementary Ed',
  'General Studies Secondary Educ',
  'Genetic Counselling',
  'Genetics',
  'Genome Science & Technology',
  'Geographical Biogeosciences',
  'Geography',
  'Geological Engineering',
  'Geology',
  'Geophysics',
  'German',
  'Germanic Studies',
  'Global Perspectives',
  'Global Supply Chain & Log',
  'Green BioProducts',
  'Guidance Studies',
  'Guitar',
  'Harpsichord',
  'Health & Society',
  'Healthcare Management',
  'Health Education',
  'Higher Education',
  'High Performance Buildings',
  'Hispanic Studies',
  'History',
  'History & Philosophy of Science',
  'Home Economics',
  'Home Economics Education',
  'Honours Math',
  'Horticulture',
  'Human Computer Interaction',
  'Human Devl, Learning & Culture',
  'Human Ecology',
  'Humanities',
  'Human Kinetics',
  'Human Nutrition',
  'Indigenous',
  'Indigenous Studies',
  'Infant Devl/Supp Child Care',
  'Information Tech & Management',
  'Information Technology',
  'InfoTech Mgmt SubSpec',
  'Inf. Technol & Intl Business',
  'Integrated Engineering',
  'Integrated Sciences',
  'Integrated Water Management',
  'Interdisciplinary Oncology',
  'Interdisciplinary Studies',
  'Interdisc. Studies Arts',
  'International Business',
  'International Nutrition',
  'International Relations',
  'International Resource Systems',
  'Int Stds In Land & Food Syst',
  'Italian',
  'Japanese',
  'Kindergarten/Primary',
  'Kinesiology',
  'Kinesiology & Health Science',
  'Korean',
  'Landscape & RecPlanning',
  'Language & Literacy Ed',
  'Latin American Studies',
  'Law',
  'Law and Society',
  'Lib, Arch and Info Stud',
  'Library Education',
  'Life Sciences',
  'Linguistics',
  'Literacy Education',
  'Management Info Systems',
  'Management Science',
  'Managerial Accounting',
  'Marketing',
  'Marketing & Intl. Business',
  'Marketing SubSpec',
  'Materials Engineering',
  'Mathematical Sciences',
  'Mathematics',
  'Mathematics & Science Educ',
  'Mathematics and Science',
  'Mathematics Education',
  'Math Fren Immersion 12mo',
  'Measurement & Evaluation',
  'Mechanical Engineering',
  'Mechatronics Design',
  'Media & Technology Studies Ed',
  'Medical Genetics',
  'Medieval Studies',
  'Microbiology',
  'Microbiology & Immunology',
  'Microbiology and Immunology',
  'Mining',
  'Mining & Mineral Process Eng',
  'Modern European Studies',
  'Modern Languages Education',
  'Multiple Entry Option January',
  'Multiple Entry Opt September',
  'Music',
  'Music Education',
  'Music History & Literature',
  'Music Scholarship',
  'Music Theory',
  'Naval Arch & Marine Eng',
  'Neuroscience',
  'Nurse Practitioner',
  'Nurse Practitioner (Family)',
  'Nursing',
  'Nutritional Sciences',
  'Occupational Hygiene',
  'Oceanography',
  'Opera',
  'Operations and Logistics',
  'Operations Research',
  'Orchestral Instrument',
  'Organ',
  'Organizational Behavior',
  'OrgBeh & HR SubSpec',
  'Org Behavior & HR',
  'Outdoor Environmental Educ',
  'Pathology/Laboratory Medicine',
  'Peridontics',
  'Pharmaceutical Science',
  'Pharmacology',
  'Philosophy',
  'Philosophy & Political Science',
  'Phys Fren Immersion 12mo',
  'Physical & Health Education',
  'Physical Education',
  'Physics',
  'Physiology',
  'Piano',
  'Plant Science',
  'Policy',
  'Political Science',
  'Political Sci(Intl Relations)',
  'Population and Public Health',
  'Post RN Program',
  'Product and Service Management',
  'Psychology',
  'Punjabi',
  'Real Estate',
  'Real Estate Management',
  'Real Property Assmt',
  'Rehabilitation Sciences',
  'Religion, Lit & Arts',
  'Religious Studies',
  'Reproductive Developmental Sc',
  'Resource Economics',
  'Resources,Enviro & Sustain',
  'Romance Studies',
  'Russian',
  'Scandinavian',
  'School Psychology',
  'Science',
  'Science & Management',
  'Science and Technology Studies',
  'Science Education',
  'Science Studies',
  'Secondary Education Dipl Pgm',
  'Social Studies Education',
  'Social Studies-Geography',
  'Social Studies-History',
  'Social Studies-Social Science',
  'Social Work',
  'Society,Cultr & Politics in Ed',
  'Sociology',
  'Soils & Environment',
  'Soil Science',
  'Spanish',
  'Special Education',
  'Speech Science',
  'Ssge Fren Immersion 12mo',
  'Sshi Fren Immer 12mo',
  'Ssss Fren Immer 12moO',
  'Statistics',
  'Strategic Management',
  'Strategic Mgmt SubSpec',
  'Strat. Mgmt. & Intl. Business',
  'Supply Chain Management',
  'Supply Chain Mgmt. & Intl. Bus',
  'Supply Chain Mgmt SubSpec',
  'Surgery',
  'Sustainability & Business',
  'Sustainability & Bus SubSpec',
  'Teaching Engl as a 2nd Lang',
  'Technology Studies Education',
  'Theatre',
  'Theatre and Film',
  'Transportation & Logistics',
  'United States Studies',
  'Urban Greenspace Management',
  'Urban Land Economics',
  'Urban Studies',
  'Urban Systems',
  'Visual & Performing Arts in Ed',
  'Visual Arts',
  'Vocational Rehab Counselling',
  'Voice',
  'Wood Products Processing',
  'Zoology',
];
